### ISSUE TITLE
HaXe compiler cannot find the library and how to fix.

### ISSUE THREAD

**Issue by notalentgeek** [sexybiggetje/haxe-linguistics#3]
So I am toying around with your library. Installed from haxelib and then tried the examples.
I got an error that stated that the compiler cannot find every type within your library.

So I got it fixed by moving test and linguistic folder to the root of the library and remove path parameter from haxelib.json.

And then I compile the examples using this command from library's root directory:
`haxe -main examples.ExampleBasicTokenizer -cpp cpp -debug`

It runs successfully.

I am quite new to HaXe, I just use it for two months now. However, I am not sure if this behavior intended.

**Comment by martijndeb** [comment]
Try specifying -cp src, that should do the trick. The classes are in a subfolder, if that works for you i'll update the docs to make that clearer. I might move them for haxelib then later on.

**Comment by notalentgeek** [comment]
`haxe -main examples.ExampleBasicTokenizer -cpp cpp -debug -cp src`
Correct this command is working with "classPath":"src" in haxelib.json

**Comment by martijndeb** [comment]
So as far for your immediate problem, this is resolved? Let me know if you have an application, or any questions.

**Comment by notalentgeek** [comment]
Yes I can now use your library. Thanks!
